import Head from 'next/head';
import { Main } from '../components';
import { Link } from '../components/layout';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />

      <Link type="button" href="/signup" variant="contained">Sign Up</Link>
      <Link type="button" href="/login" variant="contained">Login</Link>
    </div>
  );
}

export default Home;
