import { Button } from '@mui/material';
import Head from 'next/head';
import Link from 'next/link';
import { Main } from '../components';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />

      <Link href="/signup" passHref>
        <Button color="primary" variant="contained" type="button">Sign Up</Button>
      </Link>
      <Link href="/login" passHref>
        <Button color="primary" variant="contained" type="button">Login</Button>
      </Link>

    </div>
  );
}

export default Home;
