name: ci-server

on:
  push:
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: server

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
          cache-dependency-path: server/yarn.lock
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint

